# Generated by Django 4.0.5 on 2022-06-28 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vapp', '0002_jugador_delete_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='jugador',
            name='correo',
            field=models.EmailField(default=None, max_length=254),
        ),
        migrations.AddField(
            model_name='jugador',
            name='password',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='jugador',
            name='habitacion',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='jugador',
            name='nombre',
            field=models.CharField(default=None, max_length=20),
        ),
    ]
