# Generated by Django 4.0.5 on 2022-06-28 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vapp', '0007_remove_vampiro_id_alter_vampiro_hab'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vampiro',
            name='hab',
        ),
        migrations.AddField(
            model_name='vampiro',
            name='habita',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
    ]
