# Generated by Django 4.0.5 on 2022-06-28 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vapp', '0008_remove_vampiro_hab_vampiro_habita'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vampiro',
            name='password',
        ),
    ]
