# Generated by Django 4.0.5 on 2022-06-28 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vapp', '0009_remove_vampiro_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='vampiro',
            name='bajas_pendientes',
            field=models.IntegerField(default=0),
        ),
    ]
